# CLONE NODE SERVER FROM DOCKER REGISTRY
FROM node:latest

# COPY YOUR ALL OF YOUR CODE INTO A FOLDER TO BE UPLOADED IN DOCKER
COPY . /home/app

# ADD A WORKING DIRECTORY FOR DOCKER
WORKDIR /home/app/

# ADD RUNNING COMMAND
RUN npm install

# EXPOSE PORT FOR PORT MAPPING
EXPOSE 5173

# RUN THE COMMAND TO START YOUR APPLICATION
CMD "npm" "run" "dev"